name: Bug report
description: Create a bug report to help fixing issues and improve the extension.
title: "[BUG]"
labels:
  - bug
assignees:
  - jackd248
body:
  - type: input
    id: typo3-version
    attributes:
      label: TYPO3 version
      description: What TYPO3 version are you using?
      placeholder: 'e.g. 11.5.23'
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      description: What PHP version are you using?
      placeholder: 'e.g. 8.1.14'
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: Extension version
      description: What version of the extension are you using?
      placeholder: 'e.g. 0.1.0'
    validations:
      required: true
  - type: checkboxes
    id: composer-mode
    attributes:
      label: Composer mode
      description: Are you running TYPO3 in composer mode?
      options:
        - label: I'm running TYPO3 in composer mode.
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: 'e.g. macOS 11.4'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
