#!/bin/bash

## Description: Exec command for TYPO3 instance 11.
## Usage: 11
## Example: "ddev 11 composer du -o" or "ddev 11 typo3 cache:flush"

. .ddev/.typo3-setup/scripts/.utils.sh

command=$@
version=11

if [[ $command == typo3* ]]; then
    command="/usr/bin/php vendor/bin/typo3cms${command:5}"
fi

TYPO3_PATH=".Build/${version}"
if [ -d "$TYPO3_PATH" ]; then
    message magenta "[TYPO3 v${version}] ${command}"
    cd $TYPO3_PATH
    $command
else
    message red "TYPO3 binary not found for version ${version}"
fi
