#!/bin/bash

## Description: Exec command for TYPO3 instance 11.
## Usage: 11
## Example: "ddev 11 composer du -o"

. .ddev/commands/web/.utils.sh

command=$@
version=11

TYPO3_PATH=".test/${version}"
if [ -f "$TYPO3_PATH" ]; then
    message magenta "[TYPO3 v${version}] ${command}"
    cd $TYPO3_PATH
    $command
else
    message red "TYPO3 binary not found for version ${version}"
fi

