#!/bin/bash

## Description: Exec command for TYPO3 instance 12.
## Usage: 12
## Example: "ddev 12 composer du -o"

. .ddev/commands/web/.utils.sh

command=$@
version=12

TYPO3_PATH=".test/${version}"
if [ -f "$TYPO3_PATH" ]; then
    message magenta "[TYPO3 v${version}] ${command}"
    cd $TYPO3_PATH
    $command
else
    message red "TYPO3 binary not found for version ${version}"
fi

