#!/bin/bash

## Description: Exec command for TYPO3 instance 13.
## Usage: 13
## Example: "ddev 13 composer du -o"

. .ddev/commands/web/.utils.sh

command=$@
version=13

TYPO3_PATH=".test/${version}"
if [ -d "$TYPO3_PATH" ]; then
    message magenta "[TYPO3 v${version}] ${command}"
    cd $TYPO3_PATH
    $command
else
    message red "TYPO3 binary not found for version ${version}"
fi

