services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaTypo3ContentPlanner\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.ximatypo3contentplanner_toolbarcache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'ximatypo3contentplanner_toolbarcache' ]

  Xima\XimaTypo3ContentPlanner\Backend\ToolbarItems\UpdateItem:
    arguments:
      $cache: '@cache.ximatypo3contentplanner_toolbarcache'

  Xima\XimaTypo3ContentPlanner\EventListener\DrawBackendHeaderListener:
      tags:
          -   name: event.listener
              identifier: 'xima-typo3-content-planner/backend/modify-page-module-content'

  Xima\XimaTypo3ContentPlanner\EventListener\AfterPageTreeItemsPreparedListener:
      tags:
          -   name: event.listener
              identifier: 'xima-typo3-content-planner/backend/modify-page-tree-items'

  Xima\XimaTypo3ContentPlanner\EventListener\ModifyButtonBarEventListener:
    tags:
      - name: event.listener
        identifier: 'xima-typo3-content-planner/backend/modify-button-bar'

  Xima\XimaTypo3ContentPlanner\EventListener\RenderAdditionalContentToRecordListListener:
    tags:
      - name: event.listener
        identifier: 'xima-typo3-content-planner/backend/render-additional-content-to-record-list'

  Xima\XimaTypo3ContentPlanner\EventListener\ModifyRecordListRecordActionsListener:
    tags:
      - name: event.listener
        identifier: 'xima-typo3-content-planner/backend/modify-record-list-record-actions'

  Xima\XimaTypo3ContentPlanner\Command\NotifyUpdateCommand:
    tags:
      - name: console.command
        command: 'content-planner:notifiy-update'
        description: 'A command to notify users about relevant updates in the content planner.'

  Xima\XimaTypo3ContentPlanner\Command\BulkUpdateCommand:
    tags:
      - name: console.command
        command: 'content-planner:bulk-update'
        description: 'A command to perform a bulk operation to content planner entities.'

  dashboard.widget.ContentStatus-status:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              useFilter: true
      tags:
          -   name: dashboard.widget
              identifier: 'contentPlanner-status'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.status.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.status.description'
              iconIdentifier: 'flag-gray'
              height: 'large'
              width: 'medium'

  dashboard.widget.ContentStatus-current:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentStatusWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentStatusDataProvider'
          $options:
              refreshAvailable: true
              currentUserAssignee: true
      tags:
          -   name: dashboard.widget
              identifier: 'contentPlanner-current'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.current.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.current.description'
              iconIdentifier: 'flag-gray'
              height: 'medium'
              width: 'small'

  dashboard.widget.ContentStatus-comments:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentCommentWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentCommentDataProvider'
          $options:
              refreshAvailable: true
              currentUserAssignee: true
      tags:
          -   name: dashboard.widget
              identifier: 'contentPlanner-comment'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.comment.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.comment.description'
              iconIdentifier: 'content-message'
              height: 'large'
              width: 'medium'

  dashboard.widget.ContentStatus-overview:
      class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\StatusOverviewDataProvider'
          $options:
              icon: 'content-widget-chart-pie'
      tags:
          -   name: dashboard.widget
              identifier: 'contentPlanner-overview'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.overview.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.overview.description'
              iconIdentifier: 'content-widget-chart-pie'
              height: 'medium'

  Xima\XimaTypo3ContentPlanner\Widgets\Provider\CreateNoteButtonProvider:
    arguments:
      $title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.notes.button.create'

  Xima\XimaTypo3ContentPlanner\Widgets\Provider\ListNoteButtonProvider:
    arguments:
      $title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.notes.button.list'

  dashboard.widget.ContentStatus-notes:
      class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentNotesWidget'
      arguments:
          $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentNotesDataProvider'
          $buttons:
            - '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\CreateNoteButtonProvider'
            - '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ListNoteButtonProvider'
      tags:
          -   name: dashboard.widget
              identifier: 'contentPlanner-notes'
              groupNames: 'contentPlanner'
              title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.notes.title'
              description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.notes.description'
              iconIdentifier: 'content-thumbtack'
              height: 'medium'

  dashboard.widget.ContentStatus-update:
    class: 'Xima\XimaTypo3ContentPlanner\Widgets\ContentUpdateWidget'
    arguments:
      $dataProvider: '@Xima\XimaTypo3ContentPlanner\Widgets\Provider\ContentUpdateDataProvider'
    tags:
      -   name: dashboard.widget
          identifier: 'contentPlanner-update'
          groupNames: 'contentPlanner'
          title: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.update.title'
          description: 'LLL:EXT:xima_typo3_content_planner/Resources/Private/Language/locallang.xlf:widgets.contentPlanner.update.description'
          iconIdentifier: 'content-thumbtack'
          height: 'medium'
