name: CGL
on:
  push:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # @todo Use PHP 8.4 once PHP-CS-Fixer supports PHP 8.4
          php-version: 8.3
          tools: composer:v2, composer-require-checker, composer-unused, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Validation
      - name: Validate composer.json
        run: composer validate

      # Install dependencies
      - name: Add required packages
        run: composer require composer/composer:"^2.2"

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check
      - name: Reset composer.json
        run: git checkout composer.json composer.lock
      - name: Re-install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer lint:composer
      - name: Lint Editorconfig
        run: composer lint:editorconfig
      - name: Lint PHP
        run: composer lint:php -- --format checkstyle | cs2pr

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
