name: Release
on:
  push:
    tags:
      - '*'

jobs:
  ter-publish:
    uses: konradmichalik/reusable-github-actions/.github/workflows/release-typo3.yml@c460c0166a646cb65fd059c8d2f7d895ff3c787b # 0.1.0
    permissions:
      contents: write
    secrets:
      typo3-api-token: ${{ secrets.TYPO3_API_TOKEN }}
    with:
      typo3-extension-key: 'xima_typo3_content_planner'
