name: Release
on:
  push:
    tags:
      - '*'

jobs:
  ter-publish:
    uses: konradmichalik/reusable-github-actions/.github/workflows/release-typo3.yml@main
    secrets:
      typo3-api-token: ${{ secrets.TYPO3_API_TOKEN }}
    with:
      typo3-extension-key: 'xima_typo3_content_planner'
