name: OpenSSF Scorecard
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scorecard:
    uses: konradmichalik/reusable-github-actions/.github/workflows/scorecard.yml@ac6ac4d7829d8e8f85956c7474ee3ff99b98c9ed # 0.0.1
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
