name: Security
on:
  push:
    branches:
      - '**'
  pull_request: ~

jobs:
  security:
    uses: konradmichalik/reusable-github-actions/.github/workflows/security.yml@main
    permissions:
      contents: read
