name: Security
on:
  push:
    branches:
      - '**'
  pull_request: ~

jobs:
  security:
    uses: konradmichalik/reusable-github-actions/.github/workflows/security.yml@ac6ac4d7829d8e8f85956c7474ee3ff99b98c9ed # 0.0.1
    permissions:
      contents: read
