name: Tests
on:
  push:
    branches:
      - '**'

jobs:
  tests:
    uses: konradmichalik/reusable-github-actions/.github/workflows/tests.yml@ac6ac4d7829d8e8f85956c7474ee3ff99b98c9ed # 0.0.1
    with:
      php-versions: '["8.2", "8.3", "8.4", "8.5"]'
      typo3-versions: '["13.4", "14.3"]'
      dependencies: '["highest", "lowest"]'
